TYPE E_Cia402AxisState : (
	eAxisOff := 0,
	eAxisFaultResetHigh := 5,
	eAxisFaultResetLow := 6,
	eAxisSetMode := 10,
	eAxisShutdown := 20,
	eAxisSwitchOn := 30,
	eAxisEnableOperation := 40,
	eAxisServoSettling := 50,
	eAxisReadyPP := 60,
	eAxisPpTriggerHigh := 61,
	eAxisPpTriggerLow := 62,
	eAxisReadyPV := 65,
	eAxisReadyCSPHold := 70,
	eAxisReadyCSPFollow := 71,
	eAxisHalting := 80,
	eAxisDisabling := 90,
	eAxisError := 100
);
END_TYPE
